name: Deploy Quarto Book

on:
  push:
    branches: ["master"]
  workflow_dispatch:

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: quarto-dev/quarto-actions/setup@v2
      - name: Render and Publish to GitHub Pages
        run: quarto publish gh-pages --no-prompt --no-browser
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
