name: Deploy Quarto Book

on:
  push:
    branches: ["master"]
  workflow_dispatch:

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: quarto-dev/quarto-actions/setup@v2
      - name: Configure Git
        run: |
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git config --global user.name "github-actions[bot]"
      - name: Render and Publish to GitHub Pages
        run: quarto publish gh-pages --no-prompt --no-browser
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
